import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>COPY MY CODE</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  ">
        <div className="container flex flex-col items-center  gap-12 px-4  "></div>

        <Layout />
      </main>
    </>
  );
};

export default Home;
